eureka:
  client:
    serviceUrl:
      defaultZone: http://119.28.16.217:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    ip-address: 119.28.16.217
    prefer-ip-address: true
    
server:
  port: 8773
spring:
  application:
    name: service-chezu
  datasource:
    app:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://115.159.216.58:6633/sjdev?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: sjTest
      password: sjTest2962143!
    
    col:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://115.159.216.58:6633/sjdrivetest?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: sjTest
      password: sjTest2962143!
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**.xml
  type-aliases-package: com.idata365.entity