server:
  port: 7082
  
eureka:
  client:
    serviceUrl:
    defaultZone: http://119.28.16.217:8761/eureka/
#        defaultZone: http://product-eureka.idata365.com/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    
feign:
  hystrix:
    enabled: true
 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  
spring:
  application:
    name: service-shop-chezu
 
    

# 驱动配置信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://115.159.216.58:6633/devShop?useUnicode=true&useSSL=false
#    url: jdbc:mysql://115.159.216.58:6633/sjtest?useUnicode=true&useSSL=false
    username: shopdb
    password: shopDb20180427!
#    url: jdbc:mysql://127.0.0.1:6633/sjBss?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: shujin
#    password: shujin20180416!
#   driverClassName: com.mysql.jdbc.Driver

#连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
    
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
 
  type-aliases-package: com.idata365.app.entity
  
multipart:
  enabled: true