server:
  port: 9092
 
accessKeyId: LTAIPq9ykK7vst75
accessKeySecret: QZXOr94KV41I2277ADFGdOdQ1lEv8U
signUpCode: SMS_134135227
signInCode: SMS_134135229
findPwCode: SMS_134135226
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://115.159.216.58:8761/eureka/
#       defaultZone: http://product-eureka.idata365.com/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    ip-address: 115.159.216.58
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  
spring:
  application:
    name: service-sms
    
  
multipart:
  enabled: true