server:
  port: 9092
 
accessKeyId: LTAIPq9ykK7vst75
accessKeySecret: QZXOr94KV41I2277ADFGdOdQ1lEv8U
signUpCode: SMS_134135227
signInCode: SMS_134135229
findPwCode: SMS_134135226
inviteCode: SMS_134135230
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.253.162.2:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    ip-address: 120.253.162.2
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  
spring:
  application:
    name: service-sms
    
  
multipart:
  enabled: true