eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://119.28.16.217:8761/eureka/

  instance:
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
server:
  port: 9081
spring:
  application:
    name: service-col-chezu
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.216.58:6633/sjdrivetest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: sjTest
    password: sjTest2962143!
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
multipart:
    enabled: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
 
  type-aliases-package: com.idata365.col.entity
  
