server:
  port: 8761
eureka:
  instance:
    hostname: 115.159.216.58
    prefer-ip-address: true
    ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 
  server:
    enable-self-preservation: false
    